services:
  clickhouse-server:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse-server
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"  # Разрешение управления доступом
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: password
    ports:
      - "8123:8123" # HTTP интерфейс
      - "9000:9000" # TCP интерфейс
    restart: always
